---
name: Publish docker image
on:
  release:
    types: [published]
jobs:
  publish:
    name: Publish Image to Registry
    runs-on: ubuntu-18.04
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4
      - name: Login to Github registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/challenge:${{ github.sha }}
            docker.pkg.github.com/${{ github.repository }}/challenge:${{ github.ref }}
