name: Devops Challenge Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install Dependencies
        run: pip install -r requirements_dev.txt
      - name: Install tox
        run: pip install tox
      - name: Run tox
        run: tox
